### ISSUE TITLE
it suggest P1552 for economic value but that does not take a (monetary) value

### ISSUE THREAD

**Issue by egonw** [dcodings/DINGO#3]
[P1552](https://www.wikidata.org/wiki/Property:P1552) only allows to have other Wikidata items of instance [quality](https://www.wikidata.org/wiki/Q1207505). Would [P2284](https://www.wikidata.org/wiki/Property:P2284) ("price") be an option? That does take a monetary value.

**Comment by dcodings** [comment]
"Price" (P2284) has not the same semantic as "economic_value", which is the concept one wanted to define here. DINGO finally defines its own property "economic_value" and the mapping to Wikidata properties has been for the moment dropped as no strighforward semantic mapped property was found.
